Time to play:
Loading lists of data
Traceback (most recent call last):
  File "/home/dami/Inverse_GNN/train_FEMgpu.py", line 58, in <module>
    with open("/home/dami/Inverse_GNN/fenics_sol","rb") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dami/Inverse_GNN/fenics_sol'