Traceback (most recent call last):
  File "/home/dami/Inverse_GNN/train_FEMgpuGS.py", line 95, in <module>
    print("Orig data",data[1].shape)
AttributeError: 'list' object has no attribute 'shape'
Time to play:
Loading lists of data